#include<iostream>
#include<fstream>
#include<string>
#include<filesystem>
#include<algorithm>
#include<sys/stat.h>
#include"logReader.h"


logReader myReader;                             //create a logReader object
std::string baseDir = myReader.getBaseDir();    // get the base directory



int getResults(std::string filename);
void getDirList(std::string searchDate, std::string searchMach);

int main()
{
    //myReader.setMacInfo(0,"w","x");  // Just sets up machineId and Name etc from logReader.cpp  TODO needs fixing proparly.
    myReader.getMacInfo();

    std::string searchDate;
    // myReader.setMacInfo(0,"","");    // Call myReader to set up machine names.. TODO fix this to use a setup file..
    //enter main loop keep giong until user types 'q'
    do
    {
    
    std::cout << "\nEnter the date in the exact format yyyy-mm-dd  'q' to end: ";
    std::cin >> searchDate;
    
    if(searchDate == "q")
        break;
    for(int i = 0; i < 3; i++)
    {
        std::cout << std::endl << myReader.getMachName(i) << std::endl;
        getDirList(searchDate, myReader.getMachSer(i));
    }
    } while(searchDate != "q");

    return 0;
}

void getDirList(std::string searchDate, std::string searchMach)
{
    std::string str = "H192124";
    std::string str2 = searchDate;
    
    std::string str3 = "GeometryCheckTemplate6x";
    
    std::size_t found; 
    
    std::string line[11350];   // Create enough storage for all rows generated by search
    
  

    std::filesystem::directory_iterator dirToShow(baseDir);  // create directory object using basePath
    int i = 0;
    
    for (const auto& part : dirToShow) // get each element (directory) and stick it in 'part' which has type path(). Run through full list from directory
    {
        
        line[i] = part.path().string();  //convert path type to a sting type and stick it in array line[]. 
        //std::cout << i++ << " : " << part.path().string() << '\n';
        //std::cout << i << " : " << line[i] << '\n';  // print i, print print directory from line[] array
                                                        
        //found = line[i].find(str);
        found = line[i].find(searchMach);
        if (found!=std::string::npos)
        {
            //std::cout << i << " : " << line[i] << std::endl;
            line[i].append("/MPCChecks");
            std::filesystem::directory_iterator dirSub1ToShow(line[i]);  // create directory object using basePath
            //std::string linesub1[sizeof(dirSub1ToShow)];
            std::string linesub1[11350];
            int j = 0;
            for (const auto& part1 : dirSub1ToShow) // get each element (directory) and stick it in 'part1' which has type path().
            {
                linesub1[j] = part1.path().string();
                found = linesub1[j].find(str2);
                if (found!=std::string::npos)
                {                    
                    found = linesub1[j].find(str3);
                    if (found!=std::string::npos)
                    {
                        std::string filename = linesub1[j] += "\\Results.csv";
                        
                        // std::cout << j << " : " << linesub1[j] << std::endl;
                        //std::cout << j << " : " << filename << std::endl;
                        if(std::filesystem::exists(filename))
                        {
                            std::cout << "\nMPC Check\n";
                            
                            getResults(filename);
                            std::cout << "MPC Check END\n\n";
                        }
                        
                        j++;
                    }
                }
            }
    
        }
        i++;
    }  
   
}


int getResults(std::string filename)
{
    std::string line;
    std::string str = "Leaf";
    std::string str2 = "Marginal";
    std::string str3 = "CollimationGroup/MLCBacklashGroup/MLCBacklash";
    std::string str4 = "/MLCBacklash";

    
    std::replace(filename.begin(),filename.end(),'/','\\');   // Fixes Slashes in file name so they all point correct way for MicroSoft.. and add escape for c++ strings
    
    std::cout << filename << "\n\n";
  
    std::ifstream infile;
    std::size_t found;

    infile.open(filename);
    if (!infile)
    {
        std::cout << "\nUnable to open file\nor No file found for this MPC check\n\n";
        
        return 1;
    }

    
    std::cout << "Leaves with poor backlash: \n\n";

    while (!infile.eof() )
    {
        std::getline(infile, line);
        found = line.find(str);
        if (found!=std::string::npos){
            found = line.find(str2);
            if (found!=std::string::npos){
                
                line.replace(line.find(str3),str3.length(),"");  //Tidy up the output
                line.replace(line.find(str4),str4.length()," "); //Tidy up the output
                std::cout << line << '\n';
               
            }
        }

    }
    return 0;
}

